spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacancydb
    username: postgres
    password: Q12345w6
  jpa:
    hibernate:
      ddl-auto: create

telegram:
  bot:
    username: my_java_jobs_bot
    token: ${BOT_TOKEN}
    chat-id: ${CHAT_ID}


